apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis
  namespace: redis
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - name: "redis"
    match:
    - uri:
        prefix: "/redis"
    rewrite:
      uri: "/"       
    route:
    - destination:
        host: redis
        port:
          number: 6379